apiVersion: v1
kind: Service
metadata:
  name: docker-jenkins-integration-k8s-service
spec:
  selector:
     app: docker-jenkins-integration-k8s
  ports: 
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort 